apiVersion: v1
kind: Service
metadata:
  name: service-sample-nodeapp
  namespace: app-ingress
  labels:
    app: sample-node
         
spec:
  type: ClusterIP
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-node
